#cloud-config

packages:
  - curl
  - ufw

runcmd:
  - curl -sfL https://get.k3s.io | sh -
  - ufw allow 22/tcp
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  - ufw allow 6443/tcp
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw --force enable
